Task9/Task9/Models/ApplicationContext.cs
using Microsoft.EntityFrameworkCore;

namespace Task9.Models;

public class ApplicationContext : DbContext
{
    public DbSet<Student> Students { get; set; } = null!;
    public DbSet<Group> Groups { get; set; } = null!;
    public DbSet<Course> Courses { get; set; } = null!;

    public ApplicationContext(DbContextOptions<ApplicationContext> options)
        : base(options)
    {
        Database.EnsureCreated();

        if (Students.Count() == 0)
        {
            //fill students

            for (int i = 0; i < 10; i++)
            {
                Student student = new Student() { GroupId = 1, FirstName = $"Name{i}", LastName = $"LastName{i}" };
                Students.Add(student);
            }
            SaveChanges();

            for (int i = 10; i < 20; i++)
            {
                Student student = new Student() { GroupId = 4, FirstName = $"Name{i}", LastName = $"LastName{i}" };
                Students.Add(student);
            }
            SaveChanges();

            for (int i = 20; i < 30; i++)
            {
                Student student = new Student() { GroupId = 6, FirstName = $"Name{i}", LastName = $"LastName{i}" };
                Students.Add(student);
            }
            SaveChanges();

            for (int i = 30; i < 40; i++)
            {
                Student student = new Student() { GroupId = 7, FirstName = $"Name{i}", LastName = $"LastName{i}" };
                Students.Add(student);
            }
            SaveChanges();
        }


        if (Groups.Count() == 0)
        {
            //fill groups
            for (int i = 0; i < 3; i++)
            {
                Group g = new Group() { CourseId = 1, Name = $"SR-{i}" };
                Groups.Add(g);
            }
            SaveChanges();

            for (int i = 0; i < 2; i++)
            {
                Group g = new Group() { CourseId = 2, Name = $"GG-{i}" };
                Groups.Add(g);
            }
            SaveChanges();


            Group g1 = new Group() { CourseId = 3, Name = "OR-0" };
            Group g2 = new Group() { CourseId = 4, Name = "SB-0" };
            Groups.Add(g1);
            Groups.Add(g2);
            SaveChanges();
        }

        if (Courses.Count() == 0)
        {
            //fill courses
            Course c1 = new Course() { Name = "Java", Description = "Learn Java" };
            Course c2 = new Course() { Name = "PHP", Description = "Learn PHP" };
            Course c3 = new Course() { Name = "JS", Description = "Learn JS" };
            Course c4 = new Course() { Name = "Rust", Description = "Learn Rust" };
            Courses.AddRange(c1, c2, c3, c4);
            SaveChanges();
        }
    }
}

Task9/Task9/Models/Course.cs
namespace Task9.Models
{
    public class Course
    {
        public int CourseId { get; set; }
        public string? Name { get; set; }
        public string? Description { get; set; }
    }
}

Task9/Task9/Models/Group.cs
namespace Task9.Models
{
    public class Group
    {
        public int GroupId { get; set; }
        public int CourseId { get; set; }
        public string? Name { get; set; }

    }
}

Task9/Task9/Models/Student.cs
namespace Task9.Models
{
    public class Student
    {
        public int StudentId { get; set; }
        public int GroupId { get; set; }
        public string? FirstName { get; set; }
        public string? LastName { get; set; }

    }
}

Task9/Task9/Controllers/GroupController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Task9.Models;

namespace Task9.Controllers;

public class GroupController : Controller
{


    private readonly IGroupService _service;

    public GroupController(IGroupService service)
    {
        _service = service;
    }

    public IActionResult Index()
    {
        return View(_service.GetCourses());
    }

    public IActionResult Error()
    {
        return View();
    }

    public IActionResult Groups(int? id)
    {
        var group = _service.GetGroups(id);
        return View(group);
    }

    public IActionResult EditGroup(int? id)
    {
        if (id != null)
        {
            Group? group = _service.SearchGroup(id);
            if (group != null) return View(group);
        }
        return NotFound();
    }

    [HttpPost]
    public IActionResult EditGroup(Group group, int? id)
    {
        Group? oldGroup = _service.SearchGroup(id);
        oldGroup.Name = group.Name;
        _service.SaveChanges(group);
        return RedirectToAction("Index");
    }

    [HttpPost]
    public IActionResult Delete(int? id)
    {
        if (id != null)
        {
            Group? group = _service.SearchGroup(id);
            if (group != null)
            {
                bool res = _service.TryDeleteGroup(group);
                if (res)
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    return RedirectToAction("Error");
                }
            }
        }
        return NotFound();
    }
}

Task9/Task9/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Task9.Models;

namespace Task9.Controllers;

public class HomeController : Controller
{
    private readonly ICourseService _service;

    public HomeController(ICourseService service)
    {
        _service = service;
    }

    public IActionResult Index()
    {
        return View(_service.GetCourses());
    }

}

Task9/Task9/Controllers/StudentController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Task9.Models;

namespace Task9.Controllers;

public class StudentController : Controller
{

    private readonly IStudentService _service;

    public StudentController(IStudentService service)
    {
        _service = service;
    }

    public IActionResult Error()
    {
        return View();
    }

    public IActionResult Index()
    {
        return View(_service.GetCourses());
    }

    public IActionResult Students(int? id)
    {
        var student = _service.GetStudents(id);
        return View(student);
    }

    public async Task<IActionResult> EditStudent(int? id)
    {
        if (id != null)
        {
            Student? student = _service.SearchStudent(id);
            if (student != null)
            {
                return View(student);
            }
        }
        return NotFound();
    }

    [HttpPost]
    public async Task<IActionResult> EditStudent(Student student, int? id)
    {
        Student? oldStudent = _service.SearchStudent(id);
        oldStudent.FirstName = student.FirstName;
        _service.SaveChanges(oldStudent);
        return RedirectToAction("Index");
    }

    [HttpPost]
    public IActionResult Delete(int? id)
    {
        if (id != null)
        {
            Student? student = _service.SearchStudent(id);
            if (student != null)
            {
                bool res = _service.TryDeleteStudent(student);
                if (res)
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    return RedirectToAction("Error");
                }
            }
        }
        return NotFound();
    }
}

Task9/Task9/Views/Group/EditGroup.cshtml
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@model Task9.Models.Group

<!doctype html>
<html>
<head>
    <title>TASK 9</title>
    <meta charset="utf-8"/>
</head>

<body>
<h3>Editing group @Model.Name</h3>
<form asp-action="EditGroup" asp-controller="Group" asp-route-id="@Model.GroupId">
    <p>
        <label asp-for="Name">New name</label><br />
        <input type="text" asp-for="Name" />
    </p>
    <p>
        <input type="submit" value="Save" />
    </p>
</form>
</body>
</html>

Task9/Task9/Views/Group/Groups.cshtml
@{
    Layout = null;
}
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@model IEnumerable<Task9.Models.Group>

<!doctype html>
<html>
<head>
    <title>TASK 9</title>
    <meta charset="utf-8" />
</head>
<body>
    <h1>Groups</h1>
    
    @foreach (var item in Model)
    {
        <br><br/>
        <h3><a asp-action="Students" asp-controller="Student" asp-route-id="@item.GroupId">@item.Name</a></h3>
        <a asp-action="EditGroup" asp-controller="Group" asp-route-id="@item.GroupId">Change name</a>

        <form asp-controller="Group" asp-action="Delete" method="post"  asp-route-id="@item.GroupId">
            <input type="submit" value="Delete" />
        </form>
    }
</body>
</html>

Task9/Task9/Views/Group/Index.cshtml
@{
    Layout = null;
}
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@model IEnumerable<Task9.Models.Course>

<!doctype html>
<html>
<head>
    <title>TASK 9</title>
    <meta charset="utf-8"/>
</head>
<body>
    <h1>Courses</h1>
    @foreach (var item in Model)
    {
        <br><br/>
        <h2><a asp-action="Groups" asp-controller="Group" asp-route-id="@item.CourseId">@item.Name</a></h2>
    }
</body>
</html>

Task9/Task9/Views/Home/Index.cshtml
@{
    Layout = null;
}
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@model IEnumerable<Task9.Models.Course>

<!doctype html>
<html>
<head>
    <title>TASK 9</title>
    <meta charset="utf-8"/>
</head>
<body>
    <h1>Courses</h1>
    @foreach (var item in Model)
    {
        <br><br/>
        <h2><a asp-action="Groups" asp-controller="Group" asp-route-id="@item.CourseId">@item.Name</a></h2>
    }
</body>
</html>

Task9/Task9/Views/Student/EditStudent.cshtml
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@model Task9.Models.Student

<!doctype html>
<html>
<head>
    <title>TASK 9</title>
    <meta charset="utf-8"/>
</head>

<body>
<h3>Editing student @Model.FirstName</h3>
<form asp-action="EditStudent" asp-controller="Student" asp-route-id="@Model.StudentId">
    <p>
        <label asp-for="FirstName">New name</label><br />
        <input type="text" asp-for="FirstName" />
    </p>
    <p>
        <input type="submit" value="Save" />
    </p>
</form>
</body>
</html>

Task9/Task9/Views/Student/Index.cshtml
@{
    Layout = null;
}
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@model IEnumerable<Task9.Models.Course>

<!doctype html>
<html>
<head>
    <title>TASK 9</title>
    <meta charset="utf-8"/>
</head>
<body>
    <h1>Courses</h1>
    @foreach (var item in Model)
    {
        <br><br/>
        <h2><a asp-action="Groups" asp-controller="Group" asp-route-id="@item.CourseId">@item.Name</a></h2>
    }
</body>
</html>

Task9/Task9/Views/Student/Students.cshtml
@{
    Layout = null;
}
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@model IEnumerable<Task9.Models.Student>

<!doctype html>
<html>
<head>
    <title>TASK 9</title>
    <meta charset="utf-8" />
</head>
<body>
    <h1>Students</h1>
    
    @foreach (var item in Model)
    {
        <br><br/>
        <h3>@item.FirstName @item.LastName</h3>
        <a asp-action="EditStudent" asp-controller="Student" asp-route-id="@item.StudentId">Change first name</a>

        <form asp-controller="Student" asp-action="Delete" method="post"  asp-route-id="@item.StudentId">
            <input type="submit" value="Delete" />
        </form>
    }
</body>
</html>